### ISSUE TITLE
how can i compile to PDF file?

### ISSUE THREAD

**Issue by bubifengyun** [jagregory/abrash-black-book#16]
Great Work your job.
And I want to use your model to generate my own book in PDF,
Could you give some suggestions?
Thank you.

**Comment by bubifengyun** [comment]
[here](https://github.com/bubifengyun/book-yii2-dev-process), I use your template.
If infringement of your copyright, i will delete it. thank you.

**Comment by bubifengyun** [comment]
thank you, I have compiled successful.

**Comment by anqurvanillapy** [comment]
@bubifengyun You can also open the generated HTML file on Chrome and click on `Print...` for exporting PDF file. But some of the pictures may not be readable.

**Comment by bubifengyun** [comment]
@anqurvanillapy Thank you.I had seen that plugin for pdf export. I have changed to gitbook. it may be much better than this template.
