### ISSUE TITLE
Missing Chapters A through K from the CD

### ISSUE THREAD

**Issue by takyano** [jagregory/abrash-black-book#17]
This version is missing the extra chapters that were included on the CD that came with the book.

**Comment by jagregory** [comment]
Unless you can source me the chapters, there's not a lot I can do about this. Thanks for letting me know they exist though.

**Comment by ajbonner** [comment]
Once I'm sure of the legality of doing so as I have the original CD, I am happy to get these over to you.

I just need to find a CD Drive somewhere... :)
