### ISSUE TITLE
-- merged to — ?

### ISSUE THREAD

**Issue by ghost** [jagregory/abrash-black-book#28]
I think `--` gets merged to whatever that long hyphen character is called, which leads to reading code incorrectly, for example in chapter 17 I think  `while (—init_length)` should be  `while (—init_length)` ...which is github doing exactly what I said. In the latter case it should read

 `--` `init_length`

**Comment by jagregory** [comment]
Fixed in https://github.com/jagregory/abrash-black-book/releases/tag/v1.3
