### ISSUE TITLE
License type

### ISSUE THREAD

**Issue by priyadarshan** [jagregory/abrash-black-book#29]
Hi,
I was wondering  what kind of license does Graphics Programming Black Book has now?
Can one have it printed for oneself and colleagues at work (no general public)?
Thanks.

**Comment by jagregory** [comment]
The content of the Black Book is still copyright Dr Dobbs and Michael Abrash.

I can't advise you on what is or is not legal regarding the reproduction of this content in other mediums.

I would assume that as the copyright holders released the material for free online in 2001 it's probably safe to assume they're comfortable with reproductions for private use, but they didn't make the content Public Domain so the copyright still stands.

Sorry I can't be more helpful.

**Comment by priyadarshan** [comment]
Thank you, that is helpful.
