### ISSUE TITLE
Typos in Chapter 4

### ISSUE THREAD

**Issue by ghost** [jagregory/abrash-black-book#30]
There are some instances of "µs" that should be "ms" instead, in the "Dynamic RAM Refresh: The Invisible Hand" section.

> All of the PC’s system memory consists of DRAM chips. Each DRAM chip in the PC must be completely refreshed about once every four milliseconds in order to ensure the integrity of the data it stores. Obviously, it’s highly desirable that the memory in the PC retain the correct data indefinitely, so each DRAM chip in the PC must always be refreshed within 4 µs of the last refresh. Since there’s no guarantee that a given program will access each and every DRAM block once every 4 µs, the PC contains special circuitry and programming for providing DRAM refresh.

The two "4µs" instances should be ms, and also on the next section:

> The 256 addresses accessed by the refresh DMA accesses are arranged so that taken together they properly refresh all the memory in the PC. By accessing one of the 256 addresses every 15.08 µs, all of the PC’s DRAM is refreshed in 256 x 15.08 µs, or 3.86 µs, which is just about the desired 4 µs time I mentioned earlier. (Only the first 640K of memory is refreshed in the PC; video adapters and other adapters above 640K containing memory that requires refreshing must provide their own DRAM refresh in pre-AT systems.)

The "3.86 µs" and the "4µs" right after should also be ms.

I have confirmed that the original PDFs (linked on this project's main page) have the correct units.

I apologize if this is not the proper way to report this issue, but it is my first time doing so.
Thank you for your effort, by the way -- certainly more enjoyable than going through the chapter-by-chapter PDFs.

**EDIT:**

Found a few similar issues on the same chapter, in the "The Impact of the Display Adapter Cycle-Eater" section.

> Even on the EGA and VGA, the effect of the display adapter cycle-eater depends on the display mode selected. In text mode, the display adapter cycle-eater is rarely a major factor. It’s not that the cycle-eater isn’t present; however, a mere 4,000 bytes control the entire text mode display, and even with the display adapter cycle-eater it just doesn’t take that long to manipulate 4,000 bytes. Even if the display adapter cycle-eater were to cause the 8088 to take as much as 5µs per display memory access—more than five times normal—it would still take only 4,000x 2x 5µs, or 40 µs

The "40µs" should be ms, and also:

> For example, if we assume the same 5 µs per display memory access for the EGA’s high-resolution graphics mode that we assumed for text mode, it would take 26,000 x 2 x 5 µs, or 260 µs

Same thing for the "260 µs".

**Comment by jagregory** [comment]
Fixed in #32
