### ISSUE TITLE
Typos in Chapter 1

### ISSUE THREAD

**Issue by erikmartinessanches** [jagregory/abrash-black-book#39]
I'm new to x86 assembly and I'm trying to get this working on a modern x86 processor using Visual Studio 2017. However, copying in the .asm files gives several errors.

The listings in chapter 1 don't seem to be right because listing 1.3 has a line where it says "_ChecksumFile    proc near" and in listing 1.7 it says "_ChecksumChunkprocnear". I think there are multiple places where whitespaces have been messed up? For example, isn't it supposed to be "_ChecksumFile	endp" and not "_ChecksumFileendp"?

**Comment by jagregory** [comment]
Fixed in #34
