### ISSUE TITLE
many code listings do not assemble or compile in current chapter*.md files

### ISSUE THREAD

**Issue by idcrook** [jagregory/abrash-black-book#49]
There are what appear to be various transcription errors (incorrect or bad characters substituted).
Sometimes symbols have disappeared. Sometimes whitespace has been incorrectly removed causing syntax errors.

some related issues or PRs:
#28 
#44

**Comment by jagregory** [comment]
Thanks @idcrook I'll take a look at your PR.

**Comment by jagregory** [comment]
Thanks for the fixes. I've published a new release with them in: https://github.com/jagregory/abrash-black-book/releases/tag/v1.3

I've also automated the releases now, so it should be easier for me to keep on top of them now.
