### ISSUE TITLE
Pandoc fails because it cannot find 69-02.jpg

### ISSUE THREAD

**Issue by oaguy1** [jagregory/abrash-black-book#7]
After gitcloning your project, I ran `make epub` and started to run into problems. Bash spit out the error `pandoc: src/src/images/69-02.jpg: openBinaryFile: does not exist (No such file or directory)`. I looked at the markdown source and didn't find any errors, the image 69-02.jpg was referenced the same way as the other pictures. I eventually created a `src` directory within the original `src` directory and copied the `images` directory into it. This allowed me to create the book with pandoc, but is a bit of a hack.

**Comment by jagregory** [comment]
Closing as stale.
